### PR TITLE
Please allow time-1.6 to build with GHC 8

### PR DESCRIPTION
**Pull request by khibino**
I want to buid relational-record library package with stackage.

https://github.com/fpco/stackage/pull/1625

### CODE REVIEW

**Comment by khibino** [comment]
I found a issue ( https://github.com/hdbc/hdbc/issues/35 ) related to this.

**Comment by ryantm** [comment]
looks good to me

**Comment by hesselink** [comment]
Thanks! I've merged this and updated the bounds on hackage.

**Comment by ryantm** [comment]
@hesselink Thanks! Who should add HDBC and convertible back to stackage?

**Comment by hesselink** [comment]
No idea, I didn't add it, I already don't have enough time to maintain the HDBC packages as is.

**Comment by ryantm** [comment]
@hesselink I just realized we need to do a Hackage release before we can add it anyway. Would you be willing to add me as a co-maintainer on Hackage? I could help you with that then. My hackage name is "ryantm" https://wiki.haskell.org/Taking_over_a_package

**Comment by khibino** [comment]
I understand that Stackage includes packages implicitly which explicitly added packages depend on.
Hackage release is necessary anyway.

**Comment by hesselink** [comment]
I raised the bounds on hackage, so I don't see why a new release is needed. Can someone explain it to me?

**Comment by notogawa** [comment]
[This page](https://hackage.haskell.org/package/HDBC-2.4.0.1/revisions/) explains like this.
> Package maintainers and Hackage trustees are allowed to edit certain bits of package metadata after a release, without uploading a new tarball.
> Note that the tarball itself is never changed, just the metadata that is stored separately.

Cabal dependency checker references .cabal file in source tarball, and fixed metadata on hackage is ignored.

**Comment by hesselink** [comment]
Nope, cabal's dependency solver uses the updated metadata. Running `cabal update` and then `cabal install HDBC --dry-run --constraint=time>=1.6` should work without issues. It does for me.

**Comment by notogawa** [comment]
Oh, thx. I misunderstand that.

**Pull request merged**
