### PR TITLE
remove upper bound on time to support GHC 8.2.1; closes #43

### LINKED ISSUE #43: HDBC does not build with GHC 8.2.0
Reason: upper bound on `time` package is `1.7`, but GHC 8.2.0 comes with 1.8.0.1

### PR DESCRIPTION
**Pull request by ryantm**

### CODE REVIEW

**Comment by hesselink** [comment]
Thanks! I'd rather raise the bound instead though. Have you tested with GHC 8.2 at all?

**Comment by ryantm** [comment]
Okay, what do we bump it to? 

It compiles without the time upper bound, but I haven't tested it.

**Comment by khibino** [comment]
Hi, I did the test as follows using QuickCheck with time upper bound '< 1.9' and with update HDBC-postgresql ( https://github.com/hdbc/hdbc-postgresql/pull/42 ), which works fine.

https://github.com/khibino/haskell-relational-record/blob/master/rr-quickcheck/src/Test/Relational/QuickCheck/Tests.hs

**Comment by ryantm** [comment]
Okay, I updated the PR @hesselink Builds for me on 8.2.1 and 8.0.2.

**Comment by khibino** [comment]
Will the new versions of HDBC and HDBC-postgresql be uploaded?

**Comment by hesselink** [comment]
Yes, I'll try to get to it this weekend, but I'm pretty busy at the moment,
sorry.

**Comment by khibino** [comment]
@hesselink  
You directly edited the bounds on hackage in https://github.com/hdbc/hdbc/pull/36. http://hackage.haskell.org/package/HDBC-2.4.0.1/revisions/
How about coping like this?

**Comment by khibino** [comment]
bump.

**Comment by hesselink** [comment]
Finally uploaded to hackage!

**Comment by khibino** [comment]
Thanks!

**Pull request merged**
